### ISSUE TITLE
Naming conventions

### ISSUE THREAD

**Issue by mfripp** [switch-model/switch#77]
I am working with some of the set arrays, and realized that we have two different naming conventions going. We should probably standardize on one or the other.

Option 1: (index_set)_(listed_items), e.g.,
TS_TPS
PROJ_FUEL_USE_SEGMENTS
PERIOD_RELEVANT_TRANS_BUILDS

Option 2: (listed_items)\_(preposition)\_(index set), e.g.,
PROJECTS_ACTIVE_IN_TIMEPOINT
CONNECTIONS_DIRECTED_INTO_WN
ACTIVE_PERIODS_FOR_PROJECT

Option 1 is more terse, but it is a little unclear where the index name ends and the item name begins. These can also have naming conflicts with product-style sets, e.g., if  PROJ_DISPATCH_POINTS is a set of tuples from within PROJECTS x TIMEPOINTS, what should we call the indexed set of TIMEPOINTS for each PROJECT? So I would recommend standardizing on Option 2. 

With Option 2, we might also want to decide whether the name should be a noun_adjective_in_something (PROJECTS_ACTIVE_IN_TIMEPOINT) or an adjective_noun_for_something (ACTIVE_PROJECTS_FOR_TIMEPOINT). I doubt we can standardize on which preposition to use (ACTIVE_PROJECTS_FOR_TIMEPOINT or ACTIVE_PROJECTS_IN_TIMEPOINT?), but that should be OK.

Another naming issue: we sometimes write out "project" or "PROJECT" in names of components and files, and sometimes write "proj" or "PROJ". We should probably standardize on the long or the short form. I don't really have an opinion about which.

I think if we straighten these out, it will help people in learning what each set does, and guessing the name of the set they should use (or create) for a particular task.

**Comment by mfripp** [comment]
To get the ball rolling, here is some of the renaming we might do if we adopt Option 2 with the "adjective noun" convention, weakly preferring "for" as the preposition, and spelling out "project":

GEN_FUEL_USE_SEGMENTS -> FUEL_USE_SEGMENTS_FOR_GEN
PROJ_FUEL_USE_SEGMENTS -> FUEL_USE_SEGMENTS_FOR_PROJECT
RFM_LOAD_ZONES -> LOAD_ZONES_IN_RFM
RFM_P_SUPPLY_TIERS -> SUPPLY_TIERS_FOR_RFM_PERIOD
RFM_DISPATCH_POINTS -> ACTIVE_PROJECT_TIMEPOINTS_FOR_RFM_PERIOD
G_MULTI_FUELS -> FUELS_FOR_MULTI_FUEL_GENS
G_FUELS -> FUELS_FOR_GEN
G_NEW_BUILD_YEARS -> NEW_BUILDYEARS_FOR_GEN
PERIOD_RELEVANT_LOCAL_TD_BUILDS -> ACTIVE_LOCAL_TD_BUILDS_FOR_PERIOD
TS_TPS -> TPS_IN_TS
PERIOD_TS -> TS_IN_PERIOD
PERIOD_TPS -> TPS_IN_PERIOD
PERIOD_RELEVANT_TRANS_BUILDS -> ACTIVE_TRANS_BUILDS_FOR_PERIOD
CONNECTIONS_DIRECTED_INTO_WN -> INWARD_CONNECTIONS_TO_WATER_NODE
CONNECTIONS_DIRECTED_OUT_OF_WN -> OUTWARD_CONNECTIONS_FROM_WATER_NODE
LZ_PROJECTS -> PROJECTS_IN_LOAD_ZONE
PROJECT_BUILDS_OPERATIONAL_PERIODS -> OPERATIONAL_PERIODS_FOR_PROJECT_BUILD
PROJECT_PERIOD_ONLINE_BUILD_YRS -> ACTIVE_BUILDYEARS_FOR_PROJECT_PERIOD
...

**Comment by mfripp** [comment]
Here's a naming different pattern that could work for set arrays. This is a variant of Option 1 that would be pretty unambiguous: (adjective)\_(index set)\_(adjective)\_(item set). 

Here, "index set" and "item set" are a list of one or more sets, whose product is a superset of the relevant set. The first adjective is optional (often the index set will just be an unaltered copy of the original set), but the second adjective will almost always be used, to describe the kind of subset the item set is. Usually the index set will be written as singular (LOAD_ZONE), and the item set will be plural (BUILDYEARS).

In contrast, for simple sets, the name would be (adjective)\_(item set).

I think this makes more sense if I give examples:

PROJ_DISPATCH_POINTS -> ACTIVE_PROJ_TPS (simple set)
PROJ_ACTIVE_TPS -> (unchanged, set array)
PROJ_ACTIVE_PERIODS -> (unchanged)
PROJECTS_ACTIVE_IN_TIMEPOINT -> TP_ACTIVE_PROJ (or TP_ACTIVE_PROJS?)
PROJ_FUEL_USE_SEGMENTS -> (unchanged)
RFM_LOAD_ZONES ->  (unchanged)
RFM_P_SUPPLY_TIERS -> RFM_PERIOD_AVAIL_SUPPLY_TIERS
RFM_DISPATCH_POINTS -> RFM_PERIOD_ACTIVE_PROJ_TPS
PROJECTS_WITH_MULTI_FUEL -> MULTIFUEL_PROJ (simple set)
PROJ_MULTI_FUELS -> MULTIFUEL_PROJ_AVAIL_FUELS
PROJ_FUELS -> (unchanged; you can tell it's a set array because there's no leading adjective - we would never create a simple product of two existing sets; or it could be disambiguated as PROJ_AVAIL_FUELS)
PROJ_BUILDYEARS -> (unchanged, simple set)
NEW_PROJ_BUILDYEARS -> (unchanged, simple set)
PROJ_NEW_BUILD_YEARS -> NEW_PROJ_BUILDABLE_YEARS (now gone?)
PERIOD_RELEVANT_LOCAL_TD_BUILDS -> (unchanged)
TS_TPS ->  (unchanged)
PERIOD_TS -> (unchanged)
PERIOD_TPS -> (unchanged)
PERIOD_RELEVANT_TRANS_BUILDS -> (unchanged)
CONNECTIONS_DIRECTED_INTO_WN -> WATER_NODE_INWARD_CONNECTIONS
CONNECTIONS_DIRECTED_OUT_OF_WN -> WATER_NODE_OUTWARD_CONNECTIONS
LZ_PROJECTS -> LOAD_ZONE_PROJECTS (set array; how to tell?)
PROJECT_BUILDYEARS -> PROJ_BUILDYEARS (simple set; how to tell?)
PROJECT_BUILDS_OPERATIONAL_PERIODS -> PROJ_BUILDYEAR_ACTIVE_PERIODS
PROJECT_PERIOD_ONLINE_BUILD_YRS -> PROJ_PERIOD_ACTIVE_BUILDYEARS
etc....

This would be a little harder to learn to read and write than the Option 2 approach, and a little more prone to ambiguity. But it's shorter and closer to the way we've been writing code already. What do you think?

**Comment by mfripp** [comment]
More renaming thoughts: we should probably harmonize naming of BuildProj, BuildUnits, ProjCommit, CommitUnits, ProjDispatch, BuildTrans, DispatchTrans and similar. This would be one of the following: 

ProjBuild, ProjBuildUnits, ProjCommit, ProjCommitUnits, ProjDispatch, TransBuild, TransDispatch

BuildProj, BuildUnits, CommitProj, CommitUnits, DispatchProj, BuildTrans, DispatchTrans

This also extends to other specialized assets like hydrogen storage tanks.

The advantage of the first approach is that it assigns similar names to related objects (you can look at all the Proj* or Hydrogen* variables). It also fits better with things like ProjCapacity, Proj_Fixed_Costs_Annual, etc. On the other hand, the second approach is a little more natural-sounding. 

Mixing both approaches creates confusion, especially when it comes to naming new elements in specialized modules.

**Comment by mfripp** [comment]
Another naming thing:

I would recommend naming all of our expressions the same way as variables (ExpressionForSomething) instead of constraints (Expression_For_Something). When we access expressions, they are interchangeable with variables, and in fact they are sometimes replaced by variables in alternative model formulations. I think using the second convention for expressions doesn't clarify the model, and if we use the first form for variables we could reserve the second form for constraints.

**Comment by josiahjohnston** [comment]
Hi Matthias, sorry for the slow reply. 

I think your option 2 examples are more readable than what we have now (your second post). Harmonizing those decision variable names sounds like a good idea, and I prefer the VerbNoun formulation. In previous versions of Pyomo, you had to use different syntax to access the numeric value of expressions and variables during export. If that is still the case, I would lean towards naming expressions differently from variables. If that is no longer the case, I'm happy with having expressions match variables.

I propose we leave this topic open to allow other people to weigh in, but make completing the first draft of the paper a higher priority than implementing these proposals, since they won't have structural impact on the paper.

**Comment by bmaluenda** [comment]
In summary, components are going to be standardized into the following formats:

Sets: (adjective)_(item set)_(preposition)_(adjective)_(index set)
Examples:
PROJECTS_WITH_MULTI_FUEL -> MULTIFUEL_PROJ (simple set)
LZ_PROJECTS -> PROJECTS_IN_LOAD_ZONE
PROJECT_PERIOD_ONLINE_BUILD_YRS -> ACTIVE_BUILDYEARS_FOR_PROJ_PERIOD

Variables: VerbNoun
Examples:
BuildProj, BuildUnits, CommitProj, CommitUnits, DispatchProj, BuildTrans, DispatchTrans

Expressions: Use same CamelCase than variables.

PROJECTS: To be renamed to GENERATION_PROJECTS, indexed by g, and abbreviated as GEN.

Questions:
- Should the _for_ preposition be favored when naming sets? Using _in_ sounds more natural to me in several cases.
- Should a rule be set for abbreviations in set names? Proposal: The item set could be written in its long form, and the index set could be forced to use abbreviations, since it will always have been defined previously. Some short sets would not need to be abbreviated, such as PERIODS or FUELS, but longer ones would, such as GENERATION_PROJECTS or WATER_CONNECTIONS.

**Comment by josiahjohnston** [comment]
Resolved in pull request #88 and most of the discussion was in pull request #87
