### ISSUE TITLE
Removing DumpPower variable

### ISSUE THREAD

**Issue by bmaluenda** [switch-model/switch#81]
I tried to remove the DumpPower variable, but some examples increased their total cost. The Geothermal projects have to lower their baseload power outputs to exactly match demand on the first timepoints, so more fuel has to be burned in later timepoints. 

With Rodrigo we believe that the variable should be eliminated, even if it changes outputs of some examples (we would update them). A solution to reduce cost increases would be to allow free power curtailment for baseload projects. Variable O&M costs for operating the baseload plant at a certain dispatch level would need to be accounted for, but less fuel would be burned in the whole horizon of the simulation.

**Comment by josiahjohnston** [comment]
Agreed on removing DumpPower.
I checked out the examples that are impacted (copperplate0, copperplate1 and production_cost_models/unit_commit). All of the behaviors make sense and seem correct. I was confused for a minute because I hadn't noticed that baseload operational levels can now be determined for each period. 

The unit commitment example is showing some more interesting behaviors, so I'd favor updating the objective function on that one. I'd be fine with updating the objective function values in general.

If we wanted to selectively allow curtailment, I would recommend adding an explicit proj_can_curtail column to project_info.tab. I don't want all generators to curtail, especially since many generators have minimum operating levels.

**Comment by mfripp** [comment]
I agree that there should be no silent or unexpected curtailment. Sounds like DumpPower was introducing a bug -- curtailing outputs from a geothermal plant where the user expected it to run at constant power. So it sounds like the reference files should be updated to reflect the new behavior.

**Comment by bmaluenda** [comment]
DumpPower was removed from the model and examples were updated. Closing.
